plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mokano.mokahome.migrator'
    compileSdk 35

    defaultConfig {
        applicationId "com.mokano.mokahome.migrator"
        minSdk 23
        targetSdk 28
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
